services:
  mysql:
    image: mysql:8.4
    container_name: CerradoBurguer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cerrado_burguer
    ports:
      - "3307:3306"
    volumes:
      - mysql_dados:/var/lib/mysql
      - ./crud/database.sql:/docker-entrypoint-initdb.d/database.sql:ro

  php:
  build: .
  container_name: CerradoBurguer-php
  restart: always

  environment:
    DOCKER_ENV: "true"

  ports:
    - "8080:80"

  volumes:
    - ./:/var/www/html

  depends_on:
    - mysql