FROM php:8.4-apache

RUN docker-php-ext-install pdo pdo_mysql

RUN a2enmod rewrite

RUN printf '%s\n' \
'<VirtualHost *:80>' \
'    DocumentRoot /var/www/html' \
'    RedirectMatch 302 ^/$ /html/tela-inicial.html' \
'    <Directory /var/www/html>' \
'        AllowOverride All' \
'        Require all granted' \
'    </Directory>' \
'</VirtualHost>' \
> /etc/apache2/sites-available/000-default.conf